version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    env_file: .backend_env
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "443:443"
    depends_on:
      - backend
      
  jenkins:
    build:
      context: ./jenkins
      dockerfile: jenkins-dockerfile
    image: jenkins/jenkins:lts
    restart: always
    privileged: true
    user: root
    ports:
      - 50000:50000
    container_name: jenkins
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
      - /home/student73/test/ICT3103_G24:/var/jenkins_home/gitrepo

volumes:
  jenkins-docker-certs:
  jenkins-data:
    
